require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParsingsController do

  # This should return the minimal set of attributes required to create a valid
  # Parsing. As you add validations to Parsing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "link" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParsingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all parsings as @parsings" do
      parsing = Parsing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:parsings).should eq([parsing])
    end
  end

  describe "GET show" do
    it "assigns the requested parsing as @parsing" do
      parsing = Parsing.create! valid_attributes
      get :show, {:id => parsing.to_param}, valid_session
      assigns(:parsing).should eq(parsing)
    end
  end

  describe "GET new" do
    it "assigns a new parsing as @parsing" do
      get :new, {}, valid_session
      assigns(:parsing).should be_a_new(Parsing)
    end
  end

  describe "GET edit" do
    it "assigns the requested parsing as @parsing" do
      parsing = Parsing.create! valid_attributes
      get :edit, {:id => parsing.to_param}, valid_session
      assigns(:parsing).should eq(parsing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Parsing" do
        expect {
          post :create, {:parsing => valid_attributes}, valid_session
        }.to change(Parsing, :count).by(1)
      end

      it "assigns a newly created parsing as @parsing" do
        post :create, {:parsing => valid_attributes}, valid_session
        assigns(:parsing).should be_a(Parsing)
        assigns(:parsing).should be_persisted
      end

      it "redirects to the created parsing" do
        post :create, {:parsing => valid_attributes}, valid_session
        response.should redirect_to(Parsing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parsing as @parsing" do
        # Trigger the behavior that occurs when invalid params are submitted
        Parsing.any_instance.stub(:save).and_return(false)
        post :create, {:parsing => { "link" => "invalid value" }}, valid_session
        assigns(:parsing).should be_a_new(Parsing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Parsing.any_instance.stub(:save).and_return(false)
        post :create, {:parsing => { "link" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested parsing" do
        parsing = Parsing.create! valid_attributes
        # Assuming there are no other parsings in the database, this
        # specifies that the Parsing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Parsing.any_instance.should_receive(:update).with({ "link" => "MyText" })
        put :update, {:id => parsing.to_param, :parsing => { "link" => "MyText" }}, valid_session
      end

      it "assigns the requested parsing as @parsing" do
        parsing = Parsing.create! valid_attributes
        put :update, {:id => parsing.to_param, :parsing => valid_attributes}, valid_session
        assigns(:parsing).should eq(parsing)
      end

      it "redirects to the parsing" do
        parsing = Parsing.create! valid_attributes
        put :update, {:id => parsing.to_param, :parsing => valid_attributes}, valid_session
        response.should redirect_to(parsing)
      end
    end

    describe "with invalid params" do
      it "assigns the parsing as @parsing" do
        parsing = Parsing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Parsing.any_instance.stub(:save).and_return(false)
        put :update, {:id => parsing.to_param, :parsing => { "link" => "invalid value" }}, valid_session
        assigns(:parsing).should eq(parsing)
      end

      it "re-renders the 'edit' template" do
        parsing = Parsing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Parsing.any_instance.stub(:save).and_return(false)
        put :update, {:id => parsing.to_param, :parsing => { "link" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parsing" do
      parsing = Parsing.create! valid_attributes
      expect {
        delete :destroy, {:id => parsing.to_param}, valid_session
      }.to change(Parsing, :count).by(-1)
    end

    it "redirects to the parsings list" do
      parsing = Parsing.create! valid_attributes
      delete :destroy, {:id => parsing.to_param}, valid_session
      response.should redirect_to(parsings_url)
    end
  end

end
